# By: 耗子 2022/01/30
stages:
  - prepare
  - build
  - zip
  - release

cache:
  paths:
    - node_modules/

prepare-job:
  image: node:10.24.1
  stage: prepare
  script:
    - cd /builds/wepublish/dashicons/
    - npm install

build-job:
  image: node:10.24.1
  stage: build
  script:
    - cd /builds/wepublish/dashicons/
    - npm run build

zip-job:
  stage: zip
  script:
    - cd /builds/wepublish/dashicons/icon-font
    - yum install zip -y
    - zip -r icon-font.zip *
  artifacts:
    paths:
      - /builds/wepublish/dashicons/icon-font/icon-font.zip
